<?php
declare(strict_types=1);
$cfg = require __DIR__ . '/config.php';
session_name($cfg['session_name']); session_set_cookie_params(['path'=>'/cloud','httponly'=>true,'secure'=>!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off','samesite'=>'Lax']); session_start();
header('Content-Type: application/json; charset=utf-8'); header('X-Robots-Tag: noindex, nofollow, noarchive'); header('Cache-Control: no-store, private');
function cloud_json(int $status, array $data=[]): void { http_response_code($status); echo json_encode($data, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); exit; }
function cloud_db(): PDO { global $cfg; static $db; if ($db) return $db; $c=$cfg['db']; return $db=new PDO("mysql:host={$c['host']};dbname={$c['name']};charset={$c['charset']}",$c['user'],$c['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]); }
function cloud_schema(): void { $db=cloud_db(); $db->exec("CREATE TABLE IF NOT EXISTS cloud_folders (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,parent_id BIGINT UNSIGNED NULL,name VARCHAR(255) NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,deleted_at DATETIME NULL,KEY cloud_folder_parent(parent_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"); $db->exec("CREATE TABLE IF NOT EXISTS cloud_files (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,folder_id BIGINT UNSIGNED NULL,original_name VARCHAR(255) NOT NULL,storage_name CHAR(36) NOT NULL,mime_type VARCHAR(190) NOT NULL DEFAULT 'application/octet-stream',extension VARCHAR(32) NOT NULL DEFAULT '',size BIGINT UNSIGNED NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,deleted_at DATETIME NULL,UNIQUE KEY cloud_storage_name(storage_name),KEY cloud_file_folder(folder_id),KEY cloud_file_name(original_name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"); $db->exec("CREATE TABLE IF NOT EXISTS cloud_uploads (id CHAR(36) NOT NULL PRIMARY KEY,original_name VARCHAR(255) NOT NULL,storage_name CHAR(36) NOT NULL,mime_type VARCHAR(190) NOT NULL,extension VARCHAR(32) NOT NULL,total_size BIGINT UNSIGNED NOT NULL,chunk_size INT UNSIGNED NOT NULL,received_chunks INT UNSIGNED NOT NULL DEFAULT 0,folder_id BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'uploading',KEY cloud_upload_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"); }
function cloud_auth(): void { if (empty($_SESSION['cloud_auth'])) cloud_json(401,['error'=>'Сессия завершена. Войдите снова.']); }
function cloud_csrf(): string { if (empty($_SESSION['cloud_csrf'])) $_SESSION['cloud_csrf']=bin2hex(random_bytes(24)); return $_SESSION['cloud_csrf']; }
function cloud_check_csrf(): void { if (!hash_equals((string)($_SESSION['cloud_csrf']??''),(string)($_SERVER['HTTP_X_CSRF_TOKEN']??($_POST['csrf']??'')))) cloud_json(419,['error'=>'Обновите страницу и повторите действие.']); }
function cloud_body(): array { $v=json_decode(file_get_contents('php://input') ?: '{}',true); return is_array($v)?$v:[]; }
function cloud_id($id): ?int { return filter_var($id,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]) ?: null; }
function cloud_name(string $name): string { $name=trim(preg_replace('/[\x00-\x1F\x7F]/u','',$name)??''); if ($name==='' || $name==='.' || $name==='..') cloud_json(422,['error'=>'Некорректное имя.']); return mb_substr($name,0,255); }
function cloud_storage(): string { global $cfg; $p=$cfg['storage_path']; if (!is_dir($p)) @mkdir($p,0700,true); if (!is_dir($p)||!is_writable($p)) cloud_json(500,['error'=>'Не настроено хранилище файлов.']); return $p; }
function cloud_uuid(): string { return bin2hex(random_bytes(16)); }
function cloud_ext(string $name): string { return strtolower((string)pathinfo($name,PATHINFO_EXTENSION)); }
function cloud_folder(?int $id): ?array { if ($id===null) return null; $s=cloud_db()->prepare('SELECT * FROM cloud_folders WHERE id=? AND deleted_at IS NULL'); $s->execute([$id]); $r=$s->fetch(); return $r?:null; }
function cloud_file(int $id, bool $trash=false): ?array { $s=cloud_db()->prepare('SELECT * FROM cloud_files WHERE id=?'.($trash?'':' AND deleted_at IS NULL')); $s->execute([$id]); $r=$s->fetch(); return $r?:null; }
function cloud_path(array $row): string { $parts=[$row['original_name']]; $id=$row['folder_id']? (int)$row['folder_id']:null; while($id){$f=cloud_folder($id);if(!$f)break;array_unshift($parts,$f['name']);$id=$f['parent_id']?(int)$f['parent_id']:null;} return implode(' / ',$parts); }
function cloud_relative(array $row): array { return ['id'=>(int)$row['id'],'name'=>$row['original_name'],'mime'=>$row['mime_type'],'extension'=>$row['extension'],'size'=>(int)$row['size'],'folder_id'=>$row['folder_id']?(int)$row['folder_id']:null,'updated'=>$row['updated_at'],'path'=>cloud_path($row)]; }
try {
  $action=(string)($_GET['action']??'');
  if ($action==='login' && $_SERVER['REQUEST_METHOD']==='POST') { global $cfg; $body=cloud_body(); $password=(string)($body['password']??''); if (!password_verify($password,$cfg['password_hash'])) cloud_json(403,['error'=>'Неверный пароль.']); session_regenerate_id(true); $_SESSION['cloud_auth']=true; $_SESSION['cloud_csrf']=bin2hex(random_bytes(24)); cloud_json(200,['ok'=>true]); }
  if ($action==='logout') { session_destroy(); cloud_json(200,['ok'=>true]); }
  cloud_auth(); if ($_SERVER['REQUEST_METHOD']!=='GET') cloud_check_csrf();
  $db=cloud_db(); cloud_schema(); $storage=cloud_storage();
  if ($action==='me') cloud_json(200,['csrf'=>cloud_csrf(),'storage_limit'=>(int)$cfg['storage_limit']]);
  if ($action==='list') { $folder=cloud_id($_GET['folder']??null); if($folder!==null&&!cloud_folder($folder)) cloud_json(404,['error'=>'Папка не найдена.']); $s=$db->prepare('SELECT id,name,created_at,updated_at FROM cloud_folders WHERE deleted_at IS NULL AND '.($folder===null?'parent_id IS NULL':'parent_id=?').' ORDER BY name'); $folder===null?$s->execute():$s->execute([$folder]); $folders=array_map(fn($r)=>['id'=>(int)$r['id'],'name'=>$r['name'],'created'=>$r['created_at'],'updated'=>$r['updated_at']],$s->fetchAll()); $page=max(1,(int)($_GET['page']??1));$limit=min(100,max(10,(int)($_GET['limit']??50)));$off=($page-1)*$limit; $q=$folder===null?'folder_id IS NULL':'folder_id=?'; $count=$db->prepare("SELECT COUNT(*) FROM cloud_files WHERE deleted_at IS NULL AND $q");$folder===null?$count->execute():$count->execute([$folder]);$total=(int)$count->fetchColumn();$s=$db->prepare("SELECT * FROM cloud_files WHERE deleted_at IS NULL AND $q ORDER BY updated_at DESC LIMIT $limit OFFSET $off");$folder===null?$s->execute():$s->execute([$folder]); cloud_json(200,['folders'=>$folders,'files'=>array_map('cloud_relative',$s->fetchAll()),'total'=>$total,'page'=>$page,'csrf'=>cloud_csrf()]); }
  if ($action==='folder-create') { $b=cloud_body();$name=cloud_name((string)($b['name']??''));$parent=cloud_id($b['parent']??null);if($parent!==null&&!cloud_folder($parent))cloud_json(404,['error'=>'Родительская папка не найдена.']);$now=date('Y-m-d H:i:s');$s=$db->prepare('INSERT INTO cloud_folders(parent_id,name,created_at,updated_at) VALUES(?,?,?,?)');try{$s->execute([$parent,$name,$now,$now]);}catch(Throwable $e){cloud_json(409,['error'=>'Папка с таким именем уже существует.']);}cloud_json(200,['ok'=>true,'id'=>(int)$db->lastInsertId()]); }
  if ($action==='folder-rename') { $b=cloud_body();$id=cloud_id($b['id']??null);$folder=$id?cloud_folder($id):null;if(!$folder)cloud_json(404,['error'=>'Папка не найдена.']);$name=cloud_name((string)($b['name']??''));$s=$db->prepare('UPDATE cloud_folders SET name=?,updated_at=? WHERE id=?');try{$s->execute([$name,date('Y-m-d H:i:s'),$id]);}catch(Throwable $e){cloud_json(409,['error'=>'Папка с таким именем уже существует.']);}cloud_json(200,['ok'=>true]); }
  if ($action==='folder-delete') { $id=cloud_id(cloud_body()['id']??null);if(!$id||!cloud_folder($id))cloud_json(404,['error'=>'Папка не найдена.']);$now=date('Y-m-d H:i:s');$db->prepare('UPDATE cloud_folders SET deleted_at=? WHERE id=?')->execute([$now,$id]);$db->prepare('UPDATE cloud_files SET deleted_at=? WHERE folder_id=? AND deleted_at IS NULL')->execute([$now,$id]);cloud_json(200,['ok'=>true]); }
  if ($action==='upload') { if(empty($_FILES['file'])||$_FILES['file']['error']!==UPLOAD_ERR_OK)cloud_json(422,['error'=>'Не удалось получить файл.']);$f=$_FILES['file'];$name=cloud_name((string)$f['name']);$folder=cloud_id($_POST['folder']??null);if($folder!==null&&!cloud_folder($folder))cloud_json(404,['error'=>'Папка не найдена.']);$uuid=cloud_uuid();$target=$storage.'/'.$uuid;$size=(int)$f['size'];if($size>0&&disk_free_space($storage)<$size)cloud_json(507,['error'=>'Недостаточно места на диске.']);if(!move_uploaded_file($f['tmp_name'],$target))cloud_json(500,['error'=>'Не удалось сохранить файл.']);$now=date('Y-m-d H:i:s');$db->prepare('INSERT INTO cloud_files(folder_id,original_name,storage_name,mime_type,extension,size,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)')->execute([$folder,$name,$uuid,(string)($f['type']?:'application/octet-stream'),cloud_ext($name),$size,$now,$now]);cloud_json(200,['ok'=>true]); }
  if ($action==='upload-init') { $b=cloud_body();$name=cloud_name((string)($b['name']??''));$size=max(0,(int)($b['size']??0));$folder=cloud_id($b['folder']??null);if($folder!==null&&!cloud_folder($folder))cloud_json(404,['error'=>'Папка не найдена.']);$id=cloud_uuid();$storageName=cloud_uuid();$now=date('Y-m-d H:i:s');$db->prepare('INSERT INTO cloud_uploads(id,original_name,storage_name,mime_type,extension,total_size,chunk_size,folder_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$id,$name,$storageName,(string)($b['type']??'application/octet-stream'),cloud_ext($name),(string)$size,(int)$cfg['chunk_size'],$folder,$now,$now]);$part=cloud_storage().'/.parts';if(!is_dir($part))mkdir($part,0700,true);touch($part.'/'.$id.'.part');cloud_json(200,['upload_id'=>$id,'chunk_size'=>(int)$cfg['chunk_size']]); }
  if ($action==='upload-chunk') { $id=preg_replace('/[^a-f0-9]/','',(string)($_POST['upload_id']??''));$index=max(0,(int)($_POST['index']??-1));$s=$db->prepare("SELECT * FROM cloud_uploads WHERE id=? AND status='uploading'");$s->execute([$id]);$u=$s->fetch();if(!$u||empty($_FILES['chunk'])||$_FILES['chunk']['error']!==UPLOAD_ERR_OK)cloud_json(404,['error'=>'Загрузка не найдена.']);$part=$storage.'/.parts/'.$id.'.part';$in=fopen($_FILES['chunk']['tmp_name'],'rb');$out=fopen($part,'c+b');fseek($out,$index*(int)$u['chunk_size']);stream_copy_to_stream($in,$out);fclose($in);fclose($out);$received=$index+1;$db->prepare('UPDATE cloud_uploads SET received_chunks=?,updated_at=? WHERE id=?')->execute([$received,date('Y-m-d H:i:s'),$id]);cloud_json(200,['ok'=>true,'received'=>$received]); }
  if ($action==='upload-complete') { $id=preg_replace('/[^a-f0-9]/','',(string)(cloud_body()['upload_id']??''));$s=$db->prepare("SELECT * FROM cloud_uploads WHERE id=? AND status='uploading'");$s->execute([$id]);$u=$s->fetch();if(!$u)cloud_json(404,['error'=>'Загрузка не найдена.']);$part=$storage.'/.parts/'.$id.'.part';if(!is_file($part)||(int)filesize($part)!==(int)$u['total_size'])cloud_json(422,['error'=>'Не все части файла получены.']);$now=date('Y-m-d H:i:s');$db->prepare('INSERT INTO cloud_files(folder_id,original_name,storage_name,mime_type,extension,size,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)')->execute([$u['folder_id'],$u['original_name'],$u['storage_name'],$u['mime_type'],$u['extension'],$u['total_size'],$now,$now]);rename($part,$storage.'/'.$u['storage_name']);$db->prepare("UPDATE cloud_uploads SET status='complete',updated_at=? WHERE id=?")->execute([$now,$id]);cloud_json(200,['ok'=>true]); }
  if ($action==='download') { $id=cloud_id($_GET['id']??null);$f=$id?cloud_file($id):null;if(!$f||!is_file($storage.'/'.$f['storage_name']))cloud_json(404,['error'=>'Файл не найден.']);$path=$storage.'/'.$f['storage_name'];header('Content-Type: '.($f['mime_type']?:'application/octet-stream'));header('Content-Length: '.filesize($path));$dis=isset($_GET['inline'])?'inline':'attachment';header("Content-Disposition: $dis; filename*=UTF-8''".rawurlencode($f['original_name']));readfile($path);exit; }
  if ($action==='file-rename') { $b=cloud_body();$id=cloud_id($b['id']??null);$f=$id?cloud_file($id):null;if(!$f)cloud_json(404,['error'=>'Файл не найден.']);$name=cloud_name((string)($b['name']??''));if(cloud_ext($name)===''&&$f['extension']!=='')$name.='.'. $f['extension'];$db->prepare('UPDATE cloud_files SET original_name=?,updated_at=? WHERE id=?')->execute([$name,date('Y-m-d H:i:s'),$id]);cloud_json(200,['ok'=>true]); }
  if ($action==='file-delete') { $id=cloud_id(cloud_body()['id']??null);$f=$id?cloud_file($id):null;if(!$f)cloud_json(404,['error'=>'Файл не найден.']);$db->prepare('UPDATE cloud_files SET deleted_at=?,updated_at=? WHERE id=?')->execute([date('Y-m-d H:i:s'),date('Y-m-d H:i:s'),$id]);cloud_json(200,['ok'=>true]); }
  if ($action==='file-move') { $b=cloud_body();$id=cloud_id($b['id']??null);$f=$id?cloud_file($id):null;$folder=cloud_id($b['folder']??null);if(!$f||($folder!==null&&!cloud_folder($folder)))cloud_json(404,['error'=>'Файл или папка не найдены.']);$db->prepare('UPDATE cloud_files SET folder_id=?,updated_at=? WHERE id=?')->execute([$folder,date('Y-m-d H:i:s'),$id]);cloud_json(200,['ok'=>true]); }
  if ($action==='search') { $q=trim((string)($_GET['q']??''));if($q==='')cloud_json(200,['files'=>[]]);$s=$db->prepare('SELECT * FROM cloud_files WHERE deleted_at IS NULL AND original_name LIKE ? ORDER BY updated_at DESC LIMIT 100');$s->execute(['%'.$q.'%']);cloud_json(200,['files'=>array_map('cloud_relative',$s->fetchAll())]); }
  if ($action==='storage') { $s=$db->query('SELECT COALESCE(SUM(size),0) FROM cloud_files WHERE deleted_at IS NULL');cloud_json(200,['used'=>(int)$s->fetchColumn(),'limit'=>(int)$cfg['storage_limit']]); }
  if ($action==='trash') { $s=$db->query('SELECT * FROM cloud_files WHERE deleted_at IS NOT NULL ORDER BY deleted_at DESC LIMIT 100');cloud_json(200,['files'=>array_map('cloud_relative',$s->fetchAll())]); }
  if ($action==='restore') { $id=cloud_id(cloud_body()['id']??null);$f=$id?cloud_file($id,true):null;if(!$f||empty($f['deleted_at']))cloud_json(404,['error'=>'Файл не найден в корзине.']);$db->prepare('UPDATE cloud_files SET deleted_at=NULL,updated_at=? WHERE id=?')->execute([date('Y-m-d H:i:s'),$id]);cloud_json(200,['ok'=>true]); }
  if ($action==='trash-delete') { $id=cloud_id(cloud_body()['id']??null);$f=$id?cloud_file($id,true):null;if(!$f||empty($f['deleted_at']))cloud_json(404,['error'=>'Файл не найден в корзине.']);$path=$storage.'/'.$f['storage_name'];if(is_file($path))unlink($path);$db->prepare('DELETE FROM cloud_files WHERE id=?')->execute([$id]);cloud_json(200,['ok'=>true]); }
  cloud_json(404,['error'=>'Неизвестная операция.']);
} catch (Throwable $e) { error_log('Cloud: '.$e->__toString()); cloud_json(500,['error'=>'Операция не выполнена.']); }
